title = "EPRV Timeline"
author = "Jennifer Burt"
tags = ["precision", "semi-amplitude", "planets","timeline"]
description = "A figure showing the progression of radial velocity precision over time and the semi-amplitudes of the exoplanets discovered each year. RV-only detections are depicted as squares, while
planets detected first in transit and then followed up with RV facilities are depicted as circles. Figure 3 from Burt, Dumusque & Halverson 2026 : https://ui.adsabs.harvard.edu/abs/2025arXiv251101954B/abstract"
image_file = "EPRV_Timeline.png"